package com.algaworks.model;

public enum RoleEnum {

    ROLE_CADASTRAR_CATEGORIA,
    ROLE_PESQUISAR_CATEGORIA,

    ROLE_CADASTRAR_PESSOA,
    ROLE_REMOVER_PESSOA,
    ROLE_PESQUISAR_PESSOA,

    ROLE_CADASTRAR_LANCAMENTO,
    ROLE_REMOVER_LANCAMENTO,
    ROLE_PESQUISAR_LANCAMENTO,

    ROLE_CADASTRAR_BALANCETE,
    ROLE_REMOVER_BALANCETE,
    ROLE_PESQUISAR_BALANCETE,

    ROLE_CADASTRAR_BALANCO,
    ROLE_REMOVER_BALANCO,
    ROLE_PESQUISAR_BALANCO,

    ROLE_CADASTRAR_PLANEJAMENTO,
    ROLE_REMOVER_PLANEJAMENTO,
    ROLE_PESQUISAR_PLANEJAMENTO,

    ROLE_CADASTRAR_EXECUCAO,
    ROLE_REMOVER_EXECUCAO,
    ROLE_PESQUISAR_EXECUCAO,

    ROLE_CADASTRAR_INVENTARIO,
    ROLE_REMOVER_INVENTARIO,
    ROLE_PESQUISAR_INVENTARIO,

    ROLE_CADASTRAR_ASSEMBLEIA,
    ROLE_REMOVER_ASSEMBLEIA,
    ROLE_PESQUISAR_ASSEMBLEIA,

    ROLE_CADASTRAR_JUR_PROCESSO,
    ROLE_REMOVER_JUR_PROCESSO,
    ROLE_PESQUISAR_JUR_PROCESSO,

    ROLE_CADASTRAR_JUR_EVENTO,
    ROLE_REMOVER_JUR_EVENTO,
    ROLE_PESQUISAR_JUR_EVENTO,

}